package Warehouse;

public enum WarehouseAction {
    PRINT_ALL_PRODUCTS,
    PRINT_ALL_REFRIDGERATOR_PRODUCTS,
    PRINT_ALL_FREEZER_PRODUCTS,
    PRINT_ALL_SHELVES_PRODUCTS,
    PRINT_BY_EXPIRED_DATE,
    PRINT_ALL_PRODUCTS_WITH_EXPIRY_DATE_LESS_THAN_3_DAYS,
    ADD_PRODUCTS,
    REMOVE_PRODUCTS,
    ORDER_PRODUCTS,
    EXIT
}
